quarkus.http.auth.permission.mcp-endpoints.paths=/mcp/*
quarkus.http.auth.permission.mcp-endpoints.policy=authenticated
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:6274,http://localhost:6277,${app.root-url}
#quarkus.oidc.auth-server-url=
#quarkus.oidc.client-id=
quarkus.oidc.application-type=service
quarkus.oidc.resource-metadata.enabled=true
quarkus.oidc.resource-metadata.force-https-scheme=false
#app.root-url=
nextcloud.app-name=mcp-server
#nextcloud.url=
quarkus.web-bundler.dependencies.auto-import=styles
# Live-reloading disabled when testing within claude itself, because it would crash the app
quarkus.web-bundler.browser-live-reload=false
app.user-repository.file=users.json
app.mcp.app.inline-resources=true
app.root-url=http://localhost:8080